// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3nc7izSpU6EkPpHFqp5EA7jArf-BrYw',
    appId: '1:467217907727:web:d0113e4ecdec5b2d37a37a',
    messagingSenderId: '467217907727',
    projectId: 'kutay-s-app1',
    authDomain: 'kutay-s-app1.firebaseapp.com',
    databaseURL: 'https://kutay-s-app1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kutay-s-app1.appspot.com',
    measurementId: 'G-XBX79TCX0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rnYoeL9DdP50355X94CnDDQK41c81jY',
    appId: '1:467217907727:android:1c7e609e2b23222337a37a',
    messagingSenderId: '467217907727',
    projectId: 'kutay-s-app1',
    databaseURL: 'https://kutay-s-app1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kutay-s-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWb0MR2GCbpqRCML3LUTG_FtFtl_4puEE',
    appId: '1:467217907727:ios:8ff9944f340c8def37a37a',
    messagingSenderId: '467217907727',
    projectId: 'kutay-s-app1',
    databaseURL: 'https://kutay-s-app1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kutay-s-app1.appspot.com',
    iosClientId: '467217907727-pfvpn40qu344o8q21flt422uiguj4dpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
